"""changed association table

Revision ID: af3340e3f215
Revises: 
Create Date: 2025-04-07 16:04:16.669127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3340e3f215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('workout_exercise_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercise_association', schema=None) as batch_op:
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
