"""added association table

Revision ID: e7492487ae5e
Revises: f9435bd2e1ce
Create Date: 2025-04-09 08:09:59.576421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7492487ae5e'
down_revision = 'f9435bd2e1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_exercise',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id')
    )
    op.drop_table('workout_set')
    op.drop_table('workout_exercise_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_exercise_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_set',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('sets', sa.INTEGER(), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercise_association.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('workout_exercise')
    # ### end Alembic commands ###
