"""Add Workout, WorkoutExerciseAssociation, and WorkoutSet models

Revision ID: f9435bd2e1ce
Revises: af3340e3f215
Create Date: 2025-04-08 15:55:16.297803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9435bd2e1ce'
down_revision = 'af3340e3f215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercise_association.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_exercise_association', schema=None) as batch_op:
        batch_op.drop_column('sets')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercise_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('sets', sa.INTEGER(), nullable=False))

    op.drop_table('workout_set')
    # ### end Alembic commands ###
